# Generated by Django 5.0.6 on 2025-03-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('closing_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_Batch',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_Category',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('video', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_Lesson',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('user_type', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_Login',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tb_Subject',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_mark', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('batch', models.ManyToManyField(to='lmsapp.batch')),
            ],
            options={
                'db_table': 'tb_Assignment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('fees', models.FloatField()),
                ('image', models.TextField(null=True)),
                ('certificate_course', models.BooleanField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.category')),
                ('subjects', models.ManyToManyField(to='lmsapp.subject')),
            ],
            options={
                'db_table': 'tb_Course',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.TextField(null=True)),
                ('duration', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ManyToManyField(to='lmsapp.batch')),
            ],
            options={
                'db_table': 'tb_Exam',
            },
        ),
        migrations.CreateModel(
            name='Lecture_notes',
            fields=[
                ('ln_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.lesson')),
            ],
            options={
                'db_table': 'tb_Lecture_notes',
            },
        ),
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField(blank=True)),
                ('msg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='lmsapp.login')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='lmsapp.login')),
            ],
            options={
                'db_table': 'tb_Doubts',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('optionA', models.CharField(max_length=200)),
                ('optionB', models.CharField(max_length=200)),
                ('optionC', models.CharField(max_length=200)),
                ('optionD', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.exam')),
            ],
            options={
                'db_table': 'tb_Questions',
            },
        ),
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('image', models.TextField(null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.login')),
            ],
            options={
                'db_table': 'tb_Student_register',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.student_register')),
            ],
            options={
                'db_table': 'tb_Feedback',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.student_register')),
            ],
            options={
                'db_table': 'tb_Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.questions')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.student_register')),
            ],
            options={
                'db_table': 'tb_Answers',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.subject'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('assignment_file', models.TextField()),
                ('mark', models.FloatField(null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.student_register')),
            ],
            options={
                'db_table': 'tb_Submission',
            },
        ),
        migrations.CreateModel(
            name='Teacher_register',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('experience', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('image', models.TextField(null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.login')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.subject')),
            ],
            options={
                'db_table': 'tb_Teacher_register',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lmsapp.teacher_register'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.teacher_register'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ManyToManyField(to='lmsapp.teacher_register'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.teacher_register'),
        ),
    ]
